### ISSUE TITLE
Browser is not starting

### ISSUE THREAD

**Issue by C0RE1312** [gologinapp/docker#2]
I was trying to setup the geologin docker but the Orbita browser is not starting. 
My log of the start.sh: 
![Screenshot 2023-05-02 at 10 43 59](https://user-images.githubusercontent.com/80101631/235650431-59dac268-aff1-4eaa-aad5-02ebd8b82782.png)
![Screenshot 2023-05-02 at 13 09 18](https://user-images.githubusercontent.com/80101631/235650484-c75d403f-c41e-4286-982e-02bdb47f27f5.png)

When I start the docker and connect via VNC viewer I only see a black screen and after a few seconds the docker is shutting down because the nodejs puppeteer cannot connect to somewhere. 

The only thing I changed is in the start.sh the profileId and the API token.

**Comment by C0RE1312** [comment]
nvm, with the changed Dockerfile the browser started...

**Comment by bernatixer** [comment]
> nvm, with the changed Dockerfile the browser started...

Hi! What changes did you apply to the Dockerfile?
